### PR TITLE
Semver constrains, generated columns and integrity on latest versions

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [X] Have you ran tests against this code?

### Description of the Change

**Updated** after the changed suggested by @confused-Techie

Related to #91 
- Added a UNIQUE constrain (`package`, `semver`) on versions table to prevent duplicate versions of the same package;
- Added a CHECK constrain on `versions`.`semver` column to ensure its data adhere to semantic version string format (permissive, check only the first 3 numbers);
- **Introduce generated columns for versions table**
- - we have three new columns `semver_v1`, `semver_v2` and `semver_v3`  automatically generated (no need to input them on insert);
- -  each generated column is an integer related to a single version of the semver; 
- - they will be useful in the future to order versions by semver from latest to older;
- - I plan to use postgreSQL views to be able to query on ordered version to get latest versions easily on javascript code (this will be done in the next weeks if everything goes well...);
- Improve integrity on latest versions ensuring that the new inserted version is higher than the current latest one;
- -  in `insertNewPackageVersion` we first get the latest version from the db: if it's lower than the version we want to insert, we go on, otherwise throw an error.
- A new `getPackageByNameSimple` internal util has been added in `database.js` since in different parts of the module we need the package row by name; we already have something similar, but it's done for package collection outside and has a complex query; so I though to reuse this new one with a simple and faster query to avoid writing `SELECT  * FROM names WHERE name = ${name}`;
- We introduced the `user` flag to not select keys on the `packages` and `versions` tables for safety reasons, but it was only used on one function; I extended it on all other calls that does not need the pointers.

@confused-Techie this is a big one. Take your time to test slowly. First apply the new changes in the database script, then test it.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Thanks as always for contributing!

Although, one major concern before reviewing the code, is that Unique Constraint shouldn't be on `package`, `semver`, `status`.

Since really we want to prevent someone from publishing a duplicate version. Otherwise a version can be deleted and published with updates that end users will never get because the version hasn't changed from what they downloaded previously. The constraint should apply to `package`, `semver`. Essentially once a version is published it can't ever be republished.

**Comment by confused-Techie** [comment]
Additionally if you don't see it from Discord. Here's what I said there:

Alright, I've pushed an update to main, that does two things. It fixes `semverArray()` to like the docs say, only return an array of the semver values. Nothing else, it strips all the native regex match return data to only include `[ "1", "0", "1" ]` like we would expect. Additionally there was some implicit knowledge of this return structure within `engineFilter` that I've also removed, to let it use purely just the return we expect.

Otherwise the PR also includes some tests for these functions, and a small unrelated fix to the `StateStore` since I found a pretty major bug that I didn't want to forget about. If you get this latest update on your PR it should fix these failing tests

**Comment by Digitalone1** [comment]
> Thanks as always for contributing!
> 
> Although, one major concern before reviewing the code, is that Unique Constraint shouldn't be on `package`, `semver`, `status`.
> 
> Since really we want to prevent someone from publishing a duplicate version. Otherwise a version can be deleted and published with updates that end users will never get because the version hasn't changed from what they downloaded previously. The constraint should apply to `package`, `semver`. Essentially once a version is published it can't ever be republished.

You're right, you already said in #91 but I forget about it. That's nice, having only (`package`, `semver`) unique pair is more straightforward. I thought we could support the republication, but if you say that a version cannot be republished after the removal, then it's better to have only (`package`, `semver`) uniqueness.

So I'll refactor the code dropping the current constrain and adding the new one. Tonight I will work on it!

**Comment by Digitalone1** [comment]
> Additionally if you don't see it from Discord. Here's what I said there:
> 
> Alright, I've pushed an update to main, that does two things. It fixes `semverArray()` to like the docs say, only return an array of the semver values. Nothing else, it strips all the native regex match return data to only include `[ "1", "0", "1" ]` like we would expect. Additionally there was some implicit knowledge of this return structure within `engineFilter` that I've also removed, to let it use purely just the return we expect.
> 
> Otherwise the PR also includes some tests for these functions, and a small unrelated fix to the `StateStore` since I found a pretty major bug that I didn't want to forget about. If you get this latest update on your PR it should fix these failing tests

Very nice, thanks! I will merge and make the refactoring, then force push the new commit.

**Comment by Digitalone1** [comment]
I kept working on this implementing the generated columns. The latest 3 commit will fail the test because they are not implemented on the main branch yet.

`removePackageVersion` is simplified getting versions ordered from latest to older, so we don't need to compare them afterwards.

**Comment by confused-Techie** [comment]
So this is looking good, but will give it extra review. Since we do have 4 failing tests on this one, if you don't mind I'll go ahead and push to this commit, since we are able to add the DB structure to the tests even if the remote DB doesn't have them, which should then allow tests to fully pass if that's the only issue

**Comment by confused-Techie** [comment]
@Digitalone1 So I've gone ahead and pushed the alterations to the DB to the Dev DB on your PR. This sets them up, but the tests are failing, so this should be looked at if possible. Seems the virtual columns scripts have some sort of syntax error that I'm unsure of

**Comment by Digitalone1** [comment]
> @Digitalone1 So I've gone ahead and pushed the alterations to the DB to the Dev DB on your PR. This sets them up, but the tests are failing, so this should be looked at if possible. Seems the virtual columns scripts have some sort of syntax error that I'm unsure of

The syntax is correct. I tested on my local database. If it's not going on, one of the constrain is not followed by some rows which it's not a good news. 

In particular, for generated column, this means they do not follow `\d\.\d\.\d` format... 

Can you share the SQL error?

**Comment by Digitalone1** [comment]
@confused-Techie can you select count the number of versions on the production db having `semver ~ '^(\d+)(?:\.(\d+)(?:\.(\d+))?)?/'` and check if they match all the rows? Thanks.

**Comment by confused-Techie** [comment]
I'm not even attempting to run those commands on the production Database yet. But yeah you can see the command failing on our dev db on [the last test to run on this commit](https://github.com/confused-Techie/atom-backend/pull/97/checks?sha=c0bc439792f3c7ed3e634c09137d047d3681f7b8) @Digitalone1

**Comment by confused-Techie** [comment]
But if that's the case, then would the right assumption be that our test data doesn't match? Since it's failing to apply the table changes at all

**Comment by Digitalone1** [comment]
Tested on [postgresql](https://archlinux.org/packages/extra/x86_64/postgresql/) 14.6

@confused-Techie Which version are we running?

**Comment by confused-Techie** [comment]
Alright @Digitalone1 I've found a way to specify the version we use during testing. So we are now using `14.0`, this can be changed if needed, but lets see if that lets tests pass, since I can't quite seem to find what we are using in production. But if I find that it's a different version I'll make another commit to match the version we use

**Comment by confused-Techie** [comment]
Okay so @Digitalone1 I've matched the version we are using in production which is `14.5` although fair warning the tests still are failing with a syntax error for me locally. So not sure if this is just a brand new feature, or if possibly you have some kind of extension enabled that isn't available by default

**Comment by Digitalone1** [comment]
Okay, I found the reason.

The syntax for `semver_v1` generated columns is not copied good. `AS` needs the following argument to be wrapped in parentheses, but they're missing only for the first one generated column. 

That's weird because it's good written in my first commit, indeed it was working on the local db. 

It could be easily resolved copying and pasting it. 

We used this to upgrade the database version in the tests. That good anyway. 👍

**Comment by confused-Techie** [comment]
Alright, so the change in syntax on that first line is my fault. I did copy and paste, but when it failed initially I was doing some troubleshooting which was accidentally committed. My bad, and I just never fixed it after the upgrade to the DB. Sorry about that, but am glad we are keeping the same versions for the DB in prod and testing, as I could imagine that would come back to haunt us later on

**Comment by confused-Techie** [comment]
Also I went ahead since I was already here, and fixed line 853 within `database.js` as it was using `pack.name` where we were only importing `packName` as an argument for the function. So lets see if all tests pass now

**Comment by confused-Techie** [comment]
Well now knowing what line had to be fixed previously, seems the `removePackageVersion` is throwing an error, causing the catch to return. So something in this function isn't happy, no that I can confidently currently say what that is

**Comment by Digitalone1** [comment]
@confused-Techie this one with the latest commits is passing to me. I will make another PR with additional test to show the issue I pointed out on discord.

**Comment by Digitalone1** [comment]
@confused-Techie should I have to merge the progress in #104 here or are you merging this and I will continue on the test branch separately? Let me know when you can, thank.

**Comment by confused-Techie** [comment]
Okay wasn't sure of your plan. But that sounds good to me, I'll do a final review here, and merge if all is well. And you can continue on with that additional PR

**Comment by confused-Techie** [comment]
Actually while reviewing this I'm seeing usage of `getpackageName("packageName", true)` but can't seem to see where this is implemented. Am I missing something or is this outdated?

**Comment by Digitalone1** [comment]
Written in the first post. Take a look at it, I updated all the information.

That flag is for data to be passed to users, to we won't select keys and sensible data from the database.

**Review by confused-Techie — APPROVED** [review]
Love how concise you got `utils.semverArray()` while still being readable. 

Overall this looks fantastic, and I know has taken some time to get implemented. I'll get this one merged, thanks for all the hard work!

**Pull request merged**
