### PR TITLE
Trying to complete postPackages()

### PR DESCRIPTION
**Pull request by Digitalone1**
As I said in the previous PR, select what is needed rather than selecting all and pruning afterwards.

@confused-Techie let me know if there's something wrong. :)

### CODE REVIEW

**Comment by Digitalone1** [comment]
Is it only an issue of mine or codacy link in README.md is not working?

**Comment by confused-Techie** [comment]
> Is it only an issue of mine or codacy link in README.md is not working?

I'll review this PR hopefully tonight, as always thanks for the contributions.

And yeah the links are broken since I've renamed the repo, I'll go ahead and fix those right now. Thanks for pointing it out.

**Comment by confused-Techie** [comment]
So to give an update @Digitalone1 I'm going through this PR, and have two concerns.

1. Would the data returned still be able to match the expected format? Since we have to ensure that tools like `ppm` `apm` and `papm` will be able to work with the data, without change. A guide to ensure this is matching the expected data is now available in [`./docs/returns.md`](https://github.com/confused-Techie/atom-backend/blob/main/docs/returns.md)
2. Also the new SQL is giving me some issues, when testing on the currently deployed backend server. But here is my example query and the response just in case I've got something wrong.

```sql
SELECT p.pointer, p.name, p.created, p.updated, p.creation_method, p.downloads, p.stargazers_count, p.original_stargazers, p.data, JSON_AGG(v.id, v.package, v.status, v.semver, v.license, v.engine, v.meta)
FROM packages p
JOIN versions v ON p.pointer = v.package 
JOIN names n ON n.pointer = p.pointer 
WHERE n.name = '5d124ab0-a49c-4317-96d2-186a69199750'
GROUP BY p.pointer, v.package;
```

Then the results of trying to run this query:

```
ERROR:  function json_agg(integer, uuid, versionstatus, character varying, character varying, jsonb, jsonb) does not exist
LINE 1: ....stargazers_count, p.original_stargazers, p.data, JSON_AGG(v...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
SQL state: 42883
Character: 132
```

Which is strange since `JSON_AGG` is a built in function, so not sure what's causing the issue here.

But one thing I'd like to see about doing is finding a way to get you creds to try and test this yourself, to assist in your work, so that you are able to verify that PR's are able to work with the data with no issues.

**Comment by Digitalone1** [comment]
I looked into this issue, `json_build_object` is needed to type cast.

I will take a look at the expected data format.

**Comment by Digitalone1** [comment]
Regarding to tests. I will take a look into doing it on db fiddle at the moment.

Then if you find a way to let me test directly on the database, it would be appreciated. :)

**Comment by Digitalone1** [comment]
So, I gave a look at the issue.

I had to say that the ideal solution would be providing the package object full format directly from the SQL, but this is very hard. I'm not able to do it and maybe it's tough even for the most SQL expert.

Since we already have a `constructPackageObjectFull`, we can use it. I see it is only rearranging the given object from SQL. It does not prune anything and it's better this way since we want to optimize it doing less things as possible.

So we still need a type of query that does not select primary/foreign keys, than we get the SQL array and use it to construct the package object full rearranging data without the need to prune anything.

This is the correct query tested on db fiddle: https://www.db-fiddle.com/f/v8qP1NZn6MhuCmteNMC4Ay/3

Tomorrow I will update it.

Tell me what do you think @confused-Techie

**Comment by confused-Techie** [comment]
@Digitalone1 I think that new Query looks fantastic, and reducing the boiler plate it obtains would hopefully reduce the strain on the server. Or at the very least result in a more optimized approach to everything.

But we can always revisit the idea to have a query do all of this for us, but yeah I wasn't to sure on where to start, and that's why I ended up just grabbing everything and created the `constructPackageObjectFull`.

But I think this sounds great to update with that query, and still leave the other changes you made, then just after getting the object pass it through the constructor and return. Sounds like an easy merge after all that.

Thanks for looking into this one

**Comment by Digitalone1** [comment]
So I made the changes to the query. I noticed that the module for conversion to Package Object Full is not touching the keys, but I thought it's still safe to not have them in case, by mistake (a future bug, typo, I don't know), we publish the package without passing by constuctPackageObjectFull. So I left the user flag. Prevention is better than cure. @confused-Techie  Let me know what do you think.

I change also JSON_AGG to JSONB_AGG since we want to handle the object, not the string (in fact the object will be stringified afterwards).

So at this point I think PostPackges() needs to be tested.

**Comment by confused-Techie** [comment]
Alright @Digitalone1 this one required a bit of review. Everything here looks fantastic, except one thing does need to be changed, that I found during testing.

It'd be best to remove `const p_key = ...` and `const v_key = ...`, because of the way that the template literals are formed this causes a syntax error. So to have these functioning just remove the `const`s and instead structure the query like so:

```javascript
const command = await sql_storage`
      SELECT
        ${user ? sql_storage`` : sql_storage`p.pointer,`} p.name, p.created, p.updated, p.creation_method,
        p.downloads, p.stargazers_count, p.original_stargazers, p.data,
        JSONB_AGG(JSON_BUILD_OBJECT(
          ${user ? sql_storage`` : sql_storage`'id', v.id, 'package', v.package,`} 'status', v.status, 'semver', v.semver,
          'license', v.license, 'engine', v.engine, 'meta', v.meta
        )) AS versions
      FROM packages p
        JOIN versions v ON p.pointer = v.package
        JOIN names n ON n.pointer = p.pointer
      WHERE n.name = ${name}
      GROUP BY p.pointer, v.package;
    `;
```

This here will function perfectly, and lets the template literals get constructed properly. It may look a little weird, but this way I was able to get things working during testing.

So once those changes are made I'll merge to main, otherwise FANTASTIC commit. I know this was kinda a big one.

And now with the changes I made on main, as long as your system has Docker installed I'd recommend using `npm run start:dev` which will start up a local database you can test with. Then using something like [Postman](https://www.postman.com/downloads/) to query the endpoints as needed. If you'd like I can put my Postman config in this project so you don't have to go through and set everything up.

**Comment by confused-Techie** [comment]
Alright sorry @Digitalone1 was just to excited to finally get this PR merged, I may have gone ahead and just merged it myself. 

As always appreciate the fantastic contribution, and still recommend reading through my previous message to help in future development.

**Comment by Digitalone1** [comment]
> It'd be best to remove `const p_key = ...` and `const v_key = ...`, because of the way that the template literals are formed this causes a syntax error. So to have these functioning just remove the `const`s and instead structure the query like so

Which is the issue here exactly? Can't concatenate const in template literals? 
 
> And now with the changes I made on main, as long as your system has Docker installed I'd recommend using `npm run start:dev` which will start up a local database you can test with. Then using something like [Postman](https://www.postman.com/downloads/) to query the endpoints as needed. If you'd like I can put my Postman config in this project so you don't have to go through and set everything up.

I never used docker on my system unfortunately. Will try to learn it. Maybe we'll discuss on discord.

**Comment by confused-Techie** [comment]
Seems the issue is how the template literals are passed to the DB for a query, since the `postgres` or `sql_storage` will try to infer a variables type when inserted into the template literal. And afterwards refers to its value via variables passed to the database like `$1, $2, ...`. So from my understanding here, it is likely failing to identify the type of the variable properly, and has trouble mixing the partial array with the rest of the array. 

Tbh I might be a little fuzzy on the details, but from my understanding when using it like above `sql_storage``` it will then pass the values as a string into the template literals. But I'd recommend looking further at their [docs](https://github.com/porsager/postgres).

Otherwise for Docker, luckily with this method you just need it installed and running to work properly.

**Pull request merged**
