### PR TITLE
check package version and name validity

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [x] Have you ran tests against this code?
* [ ] This PR contains zero code changes.

### Description of the Change

Related to #86 

> With this new insight into how the backend originally worked, we will need to ensure that all endpoints will convert any Package Name present to lowercase.

Does it seem already done? Let me know where I have to check. It seems all locations where the names are managed in package handler now do the lowercase conversion.

> We also need to ensure that when a package is published it will also be converted to lowercase before being entered into the Database. @Digitalone1 just making sure you're aware of this issue.

Since we now do the lowercase conversion before publishing the package, it seems this is done. We have to check if in the meanwhile some new package have been entered in uppercase. You can search on the database with a regex `/[A-Z]/` (unsure the regex is not done case-insensitive).

About the PR, I covered the parts where the packageVersion is managed.

@confused-Techie there's a location where the package version is extracted but not used, I commented it with a todo in `postPackagesEventUninstall`. Should we discard it?

Besides I checked the `simpleSearch` and it seems the ILIKE is unneeded, but I don't understand the following:

```js
ORDER BY ${
  sort === "relevance" ? sqlStorage`downloads` : sqlStorage`${term}`
}
``` 

Why do we use the `term` as ORDER BY argument (if !== "relevance")? It should be a column, but it's a search keyword. Maybe you meant `sort`? 

Anyway I make a draft pull request because the local test is freezing. It's not completing. Don't know why. We need to check it out. Feel free to merge if you want...

### CODE REVIEW

**Comment by Digitalone1** [comment]
Okay, I missed a return. Now the test is completing.

**Comment by Digitalone1** [comment]
I found another location where we need to lowercase, but I had to require the query module in `git.js`.

**Comment by Digitalone1** [comment]
Since we have to decide whether to support uppercase characters for names, I convert this to draft since it has to be reworked in case we want a case insensitive search without restrictions on names.

And I don't get why it was not working since ILIKE was used for search.

**Comment by confused-Techie** [comment]
Still reviewing this one, but to answer your questions:

- I made sure to have the majority of functions start using Lowercase, but some locations such as when publishing packages may still be using mixed case, so we want to make sure that doesnt happen.
- As for `term` I think you are right, and that is a typo, but I'll read through and double check.
- And finally, we will support mixed case when publishing a package. So actually now that I say that sorry, when publishing a package we shouldnt touch the case. Since the package name can be mixed case. But all other times when we search for a package or link to it, the case shouldn't ever matter. So actually saying that on here has made me realize we might be done, other than not touching how something is published. Also I'll use that regex to check the db so thanks

**Comment by Digitalone1** [comment]
> * And finally, we will support mixed case when publishing a package. 

I will revert the changes to support mixed case. It's worth trying to test the search and find out why it was failing. ILIKE should work as case insensitive. The issue might be somewhere else.

**Comment by confused-Techie** [comment]
> > * And finally, we will support mixed case when publishing a package.
> 
> I will revert the changes to support mixed case. It's worth trying to test the search and find out why it was failing. ILIKE should work as case insensitive. The issue might be somewhere else.

Well as far as I know the search wasn't initially failing. What seemed to have been failing the other day was the linking. Since PPM assumes it can access a package by the name in the `package.json` which in our case was `Hydrogen` it would attempt to access `/api/packages/Hydrogen` which technically doesn't exist. But if we accept any case of characters, and just turn all requests to lower case then we can search the db for a uniform value. 

So I think the search itself is okay here, it was the get package details endpoint

**Comment by confused-Techie** [comment]
But otherwise just wanna say this PR is looking great so far. Just converting searches to lower case as well, which is a good idea. And if research suggests that `LIKE` is better then lets do it. Also yeah we do need better handling on the versions.

And for `postPackagesEventUninstall` that's one of the few locations our API differs with upstream. Download count is counted by version. But since we count it per object we don't do anything with the version provided during an uninstall. Lets leave it for now, but it should be on the roadmap to remove.

**Comment by Digitalone1** [comment]
> Well as far as I know the search wasn't initially failing. What seemed to have been failing the other day was the linking. Since PPM assumes it can access a package by the name in the `package.json` which in our case was `Hydrogen` it would attempt to access `/api/packages/Hydrogen` which technically doesn't exist. But if we accept any case of characters, and just turn all requests to lower case then we can search the db for a uniform value.

Can you link the line of code this happens? Sorry, it's hard to me understanding where this fails.

**Comment by Digitalone1** [comment]
> But otherwise just wanna say this PR is looking great so far. Just converting searches to lower case as well, which is a good idea. And if research suggests that `LIKE` is better then lets do it. Also yeah we do need better handling on the versions.

The problem is if we accept mixed case, we end up having `javascript-linter` and `JavaScript-Linter` as different packages (just as an example). This should be handled in some way.

That's because I was thinking of a virtual column with names converted to lowercase so the names above point to the same package, we search on it and it's faster on LIKE. The only downside it the storage, but I suppose it's better to have more storage promoting performance?

Note that virtual columns do not have to be input, therefore no change in postPackages, they are automatically generated. We should research if it's possible with PostgreSQL (I suppose they are supported).

**Comment by confused-Techie** [comment]
@Digitalone1 you do make a good point. If we don't force a case then we could have collisions. Then I suppose how about this.

When a package is published it's always converted to lower case. The user doesn't have to do this, we will allow someone to publish "JavaScript-Linter" but on the backend, it'll be saved with the name "javascript-linter".

So that way if someone tries to publish "javaSCRIPT-linter" doesn't matter, the name is taken by the previous package.

Then when I ask for "javaScript-linteR" or "JavaScript-Linter" or "JAVASCRIPT-linter" as in a type `/api/packages/javascript-linter` any one of those combos takes me to "JavaScript-Linter".

So that would mean when publishing that only the name on the name field of the package will be converted to lower case.

The name in things like the versions table can be left alone as that relies on the pointer.

---

So lets do that moving forward, because you are right we can't have collisions. Then when comparing a search everything is lower case.

---

As for the issue the other day.

Essentially when inside the install package page in Pulsar, Pulsar would reach out to `/api/packages/featured` getting a list of our features packages. Then when a user saw the package "Hydrogen" there, they clicked on the install button that was available.

The thing is, inside "Hydrogens' `package.json` is the following `name: "Hydrogen"`, but on our Database itself (because this is how we got it from Atom) the `names` table has `hydrogen`. So when the user clicked install it takes the name from the `package.json` not the normal name as seen [here](https://github.com/pulsar-edit/ppm/blob/0f03f63285b46948bffa7457439589bc013e5978/src/install.coffee#L186) in PPM. So now PPM reaches out to `/api/packages/Hydrogen`. But like mentioned before the `names` table has "hydrogen" to the user got a 404.

This is because originally Atom converted all published packages names to lower case. So that "hydrogen" = "Hydrogen" = "hydroGEN". And each would take the user to the same package. But we didn't do that causing a 404.

So by converting whatever package the URL points to, to lower case we fixed this specific issue already.

So now we do just need to make sure when a package is published the `names` table saves the name as lowercase. And whenver we take a name from the user we convert it to lower case for any comparisons or lookups

Sorry if this is at all confusing

**Comment by Digitalone1** [comment]
Okay, so we have to force lowercase on the database. No mixed case. Let's be sure about that. :)

**Comment by confused-Techie** [comment]
> Okay, so we have to force lowercase on the database. No mixed case. Let's be sure about that. :)

Yes, sorry. We force lowercase for the Name on the `NAMES` table only. Then whenever we get it from a user. Sorry for the confusion

**Comment by Digitalone1** [comment]
I suppose strings in package handler are already decoded, so no need to redecode in query module. If I'm wrong, please discard my last commit.

`query.name()` in this state is only doing lowercase, so no need to complicate the stuff adding it as dependency on `git.js` (just call `toLowerCase`).

**Comment by confused-Techie** [comment]
> I suppose strings in package handler are already decoded, so no need to redecode in query module. If I'm wrong, please discard my last commit.
> 
> `query.name()` in this state is only doing lowercase, so no need to complicate the stuff adding it as dependency on `git.js` (just call `toLowerCase`).

Where would they already be decoded? Since any decoding that was done by us in `package_handler` has been removed, and instead handed off to `query.js`. Or are you asking if they are decoded by ExpressJS itself?

**Comment by Digitalone1** [comment]
> Where would they already be decoded? Since any decoding that was done by us in `package_handler` has been removed, and instead handed off to `query.js`. Or are you asking if they are decoded by ExpressJS itself?

I don't know. If it's not done, shouldn't we do it before any call? 

I.e. I manly use PHP where there's no need to decode the query values, they are already decoded from the engine. That's why I suppose it's the same on NodeJS.

**Comment by confused-Techie** [comment]
> > Where would they already be decoded? Since any decoding that was done by us in `package_handler` has been removed, and instead handed off to `query.js`. Or are you asking if they are decoded by ExpressJS itself?
> 
> I don't know. If it's not done, shouldn't we do it before any call?
> 
> I.e. I manly use PHP where there's no need to decode the query values, they are already decoded from the engine. That's why I suppose it's the same on NodeJS.

We are ensuring to do it before any call. By using 

```javascript
let params = {
  packageName: query.packageName(req)
};
```

This way it's done before it's ever used since `query.packageName` handles it.

As for if it's done, I'll be honest I'm not 100% sure if ExpressJS handles this for us. In this PR you likely don't need to worry about it, but I'll do some research and find out myself. Would make sense that it is, but just don't want to find an edge case where it does matter, especially assuming it's not a drain on resources to do it ourself. But I'll do some testing and try to find out when I've got the chance

**Comment by Digitalone1** [comment]
> We are ensuring to do it before any call. By using
> 
> ```js
> let params = {
>   packageName: query.packageName(req)
> };
> ```

No. We were doing it only for name and q parameters. We have also other parameters to check if we should decode them.

Besides doing it in query module it's not done before any call because you already invoked a function in package_handler. 

I mean ExpressJS should have a way to decode the parameters before we handle them. It's weird the developer have to decode the parameters, usually their work is to encode before sending a request. 

> This way it's done before it's ever used since `query.packageName` handles it.
> 
> As for if it's done, I'll be honest I'm not 100% sure if ExpressJS handles this for us. In this PR you likely don't need to worry about it, but I'll do some research and find out myself. Would make sense that it is, but just don't want to find an edge case where it does matter, especially assuming it's not a drain on resources to do it ourself. But I'll do some testing and try to find out when I've got the chance

Usually the engine deals with the decode of input parameters. Php does it, it's weird ExpressJS let this task on the developer. And, anyway, if we have to do it, it has to be done way before package_handler module and for all parameters, not just the name one.

**Comment by Digitalone1** [comment]
Here we are:

https://expressjs.com/en/api.html

> NOTE: Express automatically decodes the values in req.params (using decodeURIComponent).

Same as PHP.

**Comment by confused-Techie** [comment]
> Here we are:
> 
> https://expressjs.com/en/api.html
> 
> > NOTE: Express automatically decodes the values in req.params (using decodeURIComponent).
> 
> Same as PHP.

Okay perfect, then we should be safe to remove this function from `query.packageName()`

**Comment by Digitalone1** [comment]
> > Here we are:
> > https://expressjs.com/en/api.html
> > > NOTE: Express automatically decodes the values in req.params (using decodeURIComponent).
> > 
> > 
> > Same as PHP.
> 
> Okay perfect, then we should be safe to remove this function from `query.packageName()`

Not needed, we use it to lowercase, maybe we could add other restrictions in the future and use the same function. 

As it is I change to ready for review.

**Comment by Digitalone1** [comment]
Oh, I forget to say the following line has to be removed 

https://github.com/confused-Techie/atom-backend/blob/main/src/tests/query.test.js#L62

because there's no need to test the decode since it's already done by ExpressJS.

**Comment by Digitalone1** [comment]
> Okay perfect, then we should be safe to remove this function from `query.packageName()`

@confused-Techie  I read in a wrong way the sentence above meaning to remove `query.packageName()`. You meant to remove `decodeURIComponent` from `query.packageName()` instead.

And yes, already done. And we keep `query.packageName()` in case we have to do other stuff beyond the lowercase. :+1:

**Review by confused-Techie — APPROVED** [review]
This PR looks fantastic! I really appreciate all the work done here to make sure everything works. 

Especially catching the handlers with raw requests parameters and passing those to `query.engine`, As well as making sure to keep the documentation up to date.

Although just curious why the change in some areas from `!params.versionName` to `params.versionName === false` just to ensure that it's actually false and not some other `Falsy` value like `null`, `undefined` or `0`, actually I might have answered it myself, I wonder if `0.0.x` or some variation is considered falsy, as in if it gets coerced into a number. I'll have to check but still curious what sparked that change from you.

Otherwise I'll go ahead and merge, thanks for the contribution!

**Comment by confused-Techie** [comment]
Actually, while not reported on the overview, (for some reasons tests haven't run on the recent commits, maybe github bugged out when converting back from draft?)

Anyways, looks like possibly some tests failed, can't tell if this is prior to more changes or not, so I'll test locally.

**Comment by confused-Techie** [comment]
Alright, looks like there were two issues:

* `query` was not imported into `git.js` causing any functions relying on it to fail.
* The test that you pointed out was failing, since as expected `query.packageName` was no longer handling `decodeURIComponent` which this necessitated that it did.

Since these were super simple, I've just pushed a commit to your PR for them, and will go ahead and merge.

As always thanks for contributing!

**Comment by Digitalone1** [comment]
> Although just curious why the change in some areas from `!params.versionName` to `params.versionName === false` just to ensure that it's actually false and not some other `Falsy` value like `null`, `undefined` or `0`, actually I might have answered it myself, I wonder if `0.0.x` or some variation is considered falsy, as in if it gets coerced into a number. I'll have to check but still curious what sparked that change from you.

Because in case the string is not valid or an error occurs (caught in the catch statement) the function returns false. If it's valid, it cannot be an empty string or a falsy value. :+1:

**Comment by Digitalone1** [comment]
> Although just curious why the change in some areas from `!params.versionName` to `params.versionName === false` just to ensure that it's actually false and not some other `Falsy` value like `null`, `undefined` or `0`, actually I might have answered it myself, I wonder if `0.0.x` or some variation is considered falsy, as in if it gets coerced into a number. I'll have to check but still curious what sparked that change from you.

Because in case the string is not valid or an error occurs (caught in the catch statement) the function returns false. If it's valid, it cannot be an empty string or a falsy value. +1

**Pull request merged**
