### PR TITLE
fix postgre begin() + more tests + code refactoring

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [x] Have you ran tests against this code?

### Description of the Change

Related to #91. This contains all the commits of #97 plus an additional one which shows an issue.

Which are the steps of the tests:

1. We have a starting package with 1.0.0 version.

2. Add a new 1.0.1 version. OK 

3. Insert a duplicate 1.0.1 version. This has to fail. OK
- - This fails because we compare the semver. If it's lower or equal, we exit.

- In the current state we have:
- - version 1.0.0 published
- - version 1.0.1 latest 

4. Remove 1.0.1 version. OK
- - With checks we perform, the version is marked as removed and the remaining highest published one is converted as latest.

- In the current state we have:
- - version 1.0.0 latest
- - version 1.0.1 removed

5. Check if 1.0.0 is the latest. OK

6. Insert a previous deleted package. Try to reinsert 1.0.1 version. This has to fail. OK
- -  Why we want this to fail. @confused-Techie citation: 
> if I download version 1.0.1 but there's some critical bug or secret within it, and the author pulls it off the store, then uploads again, if they kept the same version, I would personally never see an update and keep running this insecure, secret riddled version
- - This won't fail on semver comparison because the version is higher. That's why we added the (package, semver) unique constraint to prevent this insertion.

7. **The previous step fails as we want but the rollback is not applied!**
- - Before inserting the new version, we convert the current latest version to published status and this operation is saved. If the rollback worked, this was not saved.

- In the current state we have:
- - version 1.0.0 published
- - version 1.0.1 removed 

8. Show the log of `latestVer.content.versions`. We clearly see the only non removed version is published, not latest.

9. Insert a new 1.1.0 version. FAILS
- - Indeed this fails because there are no latest versions as we check inside `insertNewPackageVersion`. So this confirm the rollback is not applied. 

So I wonder why it's not working. I read the **[doc](https://github.com/porsager/postgres#readme)** of the module and it seems that whenever we go into the catch statement, the rollback should be performed. I also applied "`read write`" options, but nothing changes.

This has to be investigated because we need transactions and in the current state begin function is useless.

### CODE REVIEW

**Comment by confused-Techie** [comment]
I love the investigation done on this one! I'll start looking through to try and determine if it's something on our end causing this error, or if otherwise we need to create an issue with the upstream repo. At the very least I'm glad this is an edge case, but yeah something we don't want to be happening at all, since it should rollback. But I'm hoping this is more an instance where our error isn't being caught with our custom handler, and maybe isn't technically an error on the db side, but we will see

**Comment by confused-Techie** [comment]
Alright @Digitalone1 I've resolved this one. Essentially this will require slight modification of all previous transactions.

Essentially when we used the following 

```javascript
return await sqlStorage.begin(async () => {
```

To initiate a transaction what was happening was the because we would then call `sqlStorage` within the transaction itself, we were calling the global instance of `sqlStorage` which itself wasn't a part of a transaction. So the call went right on through and wrote to the DB. 

But if we use 

```javascript
return await sqlStorage.begin(async (sqlStorage) => {
```

To instead initiate a transaction, all subsequent calls to `sqlStorage` use the local passed version from `sqlStorage.begin` which is a part of the transaction, and as such can be rolled back. 

So essentially for all other transactions we need to pass the instance of the `sqlStorage` object that is provided by the `.begin()` function, instead of accessing the global instance.

To make this easier in the future, I may recommend that we change all transactions to instead follow the below pattern:

```javascript
return await sqlStorage
  .begin(async (sqlTrans) => {
    const latestVersion = await sqlTrans`
      SELECT *
      FROM versions
      WHERE package = ${pointer} AND status = 'latest';
    `;
  })
  .catch((err) => {
    // do something with error 
  });

```

**Comment by confused-Techie** [comment]
But if the rest of what you wanted to do in this, and the previous PR is complete, let me know so we can get all of your changes merged, I'm excited to get more testing against this, and find even more edge cases for us to worry about

**Comment by Digitalone1** [comment]
Glad you found the reason and resolved. I will test more and commit tonight!

**Comment by confused-Techie** [comment]
Maybe one #97 is merged would you wanna merge main into this PR? Just to cut down on the diff that needs to be reviewed

**Comment by Digitalone1** [comment]
> Maybe one #97 is merged would you wanna merge main into this PR? Just to cut down on the diff that needs to be reviewed

Sure I will. 👍

**Comment by Digitalone1** [comment]
@confused-Techie I added other commits with more tests ad code refactoring (merge main branch included).

If you look into them, they are pretty self explanatory. For any question, ask here or tag me on discord.

**Review by confused-Techie — APPROVED** [review]
This is a beautiful commit!

It has documentation, it has tests, it has understandable code, it has edge case testing, it has great expansion on already created functionality. Truly love everything in this PR, and appreciate that you've taken the contributing guidelines to heart!

I'll merge this one right away, and appreciate the contribution!

**Pull request merged**
